export const REDIS_USERS_CHAT_ROOM = 'REDIS_USERS_CHAT_ROOM';

export const SOCKET_USER_NAMESPACE = 'SOCKET_USER_NAMESPACE';

export const REDIS_USER_MESSAGES = 'REDIS_USER_MESSAGES';

export const CHAT_ROOM = 'CHAT_ROOM';
